#!/usr/bin/python
import os
import socket
import sys
from datetime import date

print 'usage: [system.properties file path]'

today = date.today().strftime('%Y%m%d')

hostnames=[
    't94.dong.shgt.qihoo.net',
    't95.dong.shgt.qihoo.net'
]

disks=[#'/data01',
       '/data02','/data03','/data04','/data05','/data06',
       '/data07','/data08','/data09','/data10','/data11','/data12'
       ]

properties={
    'node.current.index':0,
    'node.count':2,
    'monitor.port':2601,
    'node.httpqueryserver.port':8081,
    'node.httpqueryserver.pid':'/tmp/webcache/httpqueryserver.pid',
    'dump.processfile':'/data01/webcache/dump.process',
    'filename_bases':'16,50',
    'file_store_dirs':'/tmp/webcache/'
}

dirs=[]
for i in disks:
    if(os.system('ls %s/webcache' % (i)) == 0):
        dirs.append('%s/webcache/%s' % (i,today))

properties['file_store_dirs']=','.join(dirs)
if(len(dirs) > 0):
    properties['dump.processfile']=dirs[0]+'/dump.process'
    properties['node.httpqueryserver.pid']=dirs[0]+'/../httpqueryserver.pid'
    properties['file_blacklist']=dirs[0]+'/../blacklist'

hostn = socket.gethostname()
idx=0
try:
    idx =  hostnames.index(hostn)
except:
    print '#invalid host'
properties['node.current.index']=idx


#print properties
f = open(sys.argv[1], 'w')
f.write('#generated by %s\n'%(sys.argv[0]))
for (k,v) in properties.iteritems():
    print k,'=',v
    f.write(k+'='+str(v)+'\n')

