// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hdfs_protos.proto

package com.oneboxtech.se.webcache.model.proto;

public final class WebCacheDocProtos {
  private WebCacheDocProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WebCacheDocOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 version = 1;
    boolean hasVersion();
    int getVersion();
    
    // required int64 crawl_time = 5;
    boolean hasCrawlTime();
    long getCrawlTime();
    
    // required string url = 10;
    boolean hasUrl();
    String getUrl();
    
    // optional bytes utf8_page = 15;
    boolean hasUtf8Page();
    com.google.protobuf.ByteString getUtf8Page();
    
    // optional bytes gzip_compressed_utf8_page = 20;
    boolean hasGzipCompressedUtf8Page();
    com.google.protobuf.ByteString getGzipCompressedUtf8Page();
    
    // optional bytes title = 25;
    boolean hasTitle();
    com.google.protobuf.ByteString getTitle();
  }
  public static final class WebCacheDoc extends
      com.google.protobuf.GeneratedMessage
      implements WebCacheDocOrBuilder {
    // Use WebCacheDoc.newBuilder() to construct.
    private WebCacheDoc(Builder builder) {
      super(builder);
    }
    private WebCacheDoc(boolean noInit) {}
    
    private static final WebCacheDoc defaultInstance;
    public static WebCacheDoc getDefaultInstance() {
      return defaultInstance;
    }
    
    public WebCacheDoc getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.internal_static_webcache_proto_WebCacheDoc_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.internal_static_webcache_proto_WebCacheDoc_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getVersion() {
      return version_;
    }
    
    // required int64 crawl_time = 5;
    public static final int CRAWL_TIME_FIELD_NUMBER = 5;
    private long crawlTime_;
    public boolean hasCrawlTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getCrawlTime() {
      return crawlTime_;
    }
    
    // required string url = 10;
    public static final int URL_FIELD_NUMBER = 10;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes utf8_page = 15;
    public static final int UTF8_PAGE_FIELD_NUMBER = 15;
    private com.google.protobuf.ByteString utf8Page_;
    public boolean hasUtf8Page() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getUtf8Page() {
      return utf8Page_;
    }
    
    // optional bytes gzip_compressed_utf8_page = 20;
    public static final int GZIP_COMPRESSED_UTF8_PAGE_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString gzipCompressedUtf8Page_;
    public boolean hasGzipCompressedUtf8Page() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getGzipCompressedUtf8Page() {
      return gzipCompressedUtf8Page_;
    }
    
    // optional bytes title = 25;
    public static final int TITLE_FIELD_NUMBER = 25;
    private com.google.protobuf.ByteString title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.google.protobuf.ByteString getTitle() {
      return title_;
    }
    
    private void initFields() {
      version_ = 0;
      crawlTime_ = 0L;
      url_ = "";
      utf8Page_ = com.google.protobuf.ByteString.EMPTY;
      gzipCompressedUtf8Page_ = com.google.protobuf.ByteString.EMPTY;
      title_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCrawlTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(5, crawlTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(10, getUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(15, utf8Page_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(20, gzipCompressedUtf8Page_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(25, title_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, crawlTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, utf8Page_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, gzipCompressedUtf8Page_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(25, title_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDocOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.internal_static_webcache_proto_WebCacheDoc_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.internal_static_webcache_proto_WebCacheDoc_fieldAccessorTable;
      }
      
      // Construct using com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        crawlTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        utf8Page_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        gzipCompressedUtf8Page_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        title_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc.getDescriptor();
      }
      
      public com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc getDefaultInstanceForType() {
        return com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc.getDefaultInstance();
      }
      
      public com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc build() {
        com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc buildPartial() {
        com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc result = new com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.crawlTime_ = crawlTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.utf8Page_ = utf8Page_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.gzipCompressedUtf8Page_ = gzipCompressedUtf8Page_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.title_ = title_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc) {
          return mergeFrom((com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc other) {
        if (other == com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasCrawlTime()) {
          setCrawlTime(other.getCrawlTime());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (other.hasUtf8Page()) {
          setUtf8Page(other.getUtf8Page());
        }
        if (other.hasGzipCompressedUtf8Page()) {
          setGzipCompressedUtf8Page(other.getGzipCompressedUtf8Page());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCrawlTime()) {
          
          return false;
        }
        if (!hasUrl()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000002;
              crawlTime_ = input.readInt64();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000004;
              url_ = input.readBytes();
              break;
            }
            case 122: {
              bitField0_ |= 0x00000008;
              utf8Page_ = input.readBytes();
              break;
            }
            case 162: {
              bitField0_ |= 0x00000010;
              gzipCompressedUtf8Page_ = input.readBytes();
              break;
            }
            case 202: {
              bitField0_ |= 0x00000020;
              title_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 version = 1;
      private int version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getVersion() {
        return version_;
      }
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }
      
      // required int64 crawl_time = 5;
      private long crawlTime_ ;
      public boolean hasCrawlTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getCrawlTime() {
        return crawlTime_;
      }
      public Builder setCrawlTime(long value) {
        bitField0_ |= 0x00000002;
        crawlTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearCrawlTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        crawlTime_ = 0L;
        onChanged();
        return this;
      }
      
      // required string url = 10;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        url_ = value;
        onChanged();
      }
      
      // optional bytes utf8_page = 15;
      private com.google.protobuf.ByteString utf8Page_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasUtf8Page() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getUtf8Page() {
        return utf8Page_;
      }
      public Builder setUtf8Page(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        utf8Page_ = value;
        onChanged();
        return this;
      }
      public Builder clearUtf8Page() {
        bitField0_ = (bitField0_ & ~0x00000008);
        utf8Page_ = getDefaultInstance().getUtf8Page();
        onChanged();
        return this;
      }
      
      // optional bytes gzip_compressed_utf8_page = 20;
      private com.google.protobuf.ByteString gzipCompressedUtf8Page_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasGzipCompressedUtf8Page() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getGzipCompressedUtf8Page() {
        return gzipCompressedUtf8Page_;
      }
      public Builder setGzipCompressedUtf8Page(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        gzipCompressedUtf8Page_ = value;
        onChanged();
        return this;
      }
      public Builder clearGzipCompressedUtf8Page() {
        bitField0_ = (bitField0_ & ~0x00000010);
        gzipCompressedUtf8Page_ = getDefaultInstance().getGzipCompressedUtf8Page();
        onChanged();
        return this;
      }
      
      // optional bytes title = 25;
      private com.google.protobuf.ByteString title_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.google.protobuf.ByteString getTitle() {
        return title_;
      }
      public Builder setTitle(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000020);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:webcache_proto.WebCacheDoc)
    }
    
    static {
      defaultInstance = new WebCacheDoc(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:webcache_proto.WebCacheDoc)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_webcache_proto_WebCacheDoc_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webcache_proto_WebCacheDoc_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021hdfs_protos.proto\022\016webcache_proto\"\204\001\n\013" +
      "WebCacheDoc\022\017\n\007version\030\001 \001(\005\022\022\n\ncrawl_ti" +
      "me\030\005 \002(\003\022\013\n\003url\030\n \002(\t\022\021\n\tutf8_page\030\017 \001(\014" +
      "\022!\n\031gzip_compressed_utf8_page\030\024 \001(\014\022\r\n\005t" +
      "itle\030\031 \001(\014B;\n&com.oneboxtech.se.webcache" +
      ".model.protoB\021WebCacheDocProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_webcache_proto_WebCacheDoc_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_webcache_proto_WebCacheDoc_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_webcache_proto_WebCacheDoc_descriptor,
              new java.lang.String[] { "Version", "CrawlTime", "Url", "Utf8Page", "GzipCompressedUtf8Page", "Title", },
              com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc.class,
              com.oneboxtech.se.webcache.model.proto.WebCacheDocProtos.WebCacheDoc.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
